# Generated by Django 3.0.8 on 2021-10-30 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('user_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('priority', models.CharField(default='no', max_length=255)),
                ('created_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='UserPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_id', models.IntegerField(default=0)),
                ('title_url', models.CharField(default='', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('value_url', models.CharField(default='', max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('value1_url', models.CharField(default='', max_length=100)),
                ('value1', models.CharField(blank=True, max_length=255, null=True)),
                ('value2_url', models.CharField(default='', max_length=100)),
                ('value2', models.CharField(blank=True, max_length=255, null=True)),
                ('value3_url', models.CharField(default='', max_length=100)),
                ('value3', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
