# Generated by Django 3.0.8 on 2021-10-30 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='priority',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
