# Generated by Django 3.0.8 on 2021-10-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211030_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='site',
            field=models.CharField(default='', max_length=255),
        ),
    ]
