# Generated by Django 3.0.8 on 2021-11-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userdetail_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('url', models.CharField(default='', max_length=255)),
                ('status', models.CharField(default='no', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OperationPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('url', models.CharField(default='', max_length=255)),
                ('status', models.CharField(default='no', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='UserPriority',
        ),
    ]
