# Generated by Django 3.0.8 on 2021-11-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20211101_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpermission',
            name='url1',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notificationpermission',
            name='url2',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notificationpermission',
            name='url3',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='operationpermission',
            name='url1',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='operationpermission',
            name='url2',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='operationpermission',
            name='url3',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
