# Generated by Django 3.0.8 on 2021-11-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20211101_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpermission',
            name='url4',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='operationpermission',
            name='url4',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
