# Generated by Django 3.0.8 on 2021-11-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20211101_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationpermission',
            name='url_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='operationpermission',
            name='url_name1',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='operationpermission',
            name='url_name2',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='operationpermission',
            name='url_name3',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='operationpermission',
            name='url_name4',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
