# Generated by Django 3.0.8 on 2021-11-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20211101_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationpermission',
            old_name='status',
            new_name='main_admin',
        ),
        migrations.RenameField(
            model_name='operationpermission',
            old_name='status',
            new_name='main_admin',
        ),
        migrations.RemoveField(
            model_name='notificationpermission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='operationpermission',
            name='user',
        ),
        migrations.AddField(
            model_name='notificationpermission',
            name='main_staff',
            field=models.CharField(default='no', max_length=255),
        ),
        migrations.AddField(
            model_name='notificationpermission',
            name='site_admin',
            field=models.CharField(default='no', max_length=255),
        ),
        migrations.AddField(
            model_name='notificationpermission',
            name='site_staff',
            field=models.CharField(default='no', max_length=255),
        ),
        migrations.AddField(
            model_name='operationpermission',
            name='main_staff',
            field=models.CharField(default='no', max_length=255),
        ),
        migrations.AddField(
            model_name='operationpermission',
            name='site_admin',
            field=models.CharField(default='no', max_length=255),
        ),
        migrations.AddField(
            model_name='operationpermission',
            name='site_staff',
            field=models.CharField(default='no', max_length=255),
        ),
        migrations.AlterField(
            model_name='notificationpermission',
            name='description',
            field=models.CharField(default='no', max_length=255),
        ),
        migrations.AlterField(
            model_name='operationpermission',
            name='description',
            field=models.CharField(default='no', max_length=255),
        ),
    ]
