# Generated by Django 3.0.8 on 2021-11-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20211101_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationpermission',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
