# Generated by Django 3.0.8 on 2021-11-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20211102_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
