# Generated by Django 3.0.8 on 2021-11-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_userdetail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationpermission',
            name='url_name11',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
