# Generated by Django 3.0.8 on 2022-07-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_operationpermission_url_name11'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationpermission',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
