# Generated by Django 3.0.8 on 2022-10-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_operationpermission_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='active_status',
            field=models.CharField(blank=True, default='yes', max_length=255, null=True),
        ),
    ]
