# Generated by Django 3.0.8 on 2021-11-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='entry_by',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='site',
            name='user_site',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='stockcategory',
            name='entry_by',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='suppliercategory',
            name='entry_by',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='uom',
            name='entry_by',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='entry_by',
            field=models.CharField(default='', max_length=255),
        ),
    ]
