# Generated by Django 3.0.8 on 2021-11-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0002_auto_20211102_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='stock_site',
            field=models.CharField(default='', max_length=255),
        ),
    ]
