# Generated by Django 3.0.8 on 2021-11-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0003_stockentry_stock_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='entry_by',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
