# Generated by Django 3.0.8 on 2021-11-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0004_supplier_entry_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='entry_by',
            field=models.CharField(default='', max_length=255),
        ),
    ]
