# Generated by Django 3.0.8 on 2021-11-04 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0006_stockentry_entry_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_topic', models.CharField(max_length=255)),
                ('content_id', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('from_site', models.CharField(max_length=255)),
                ('from_user', models.CharField(max_length=255)),
                ('content_val', models.CharField(max_length=255)),
                ('content_val1', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('content_val2', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('content_val3', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('entry_date', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('date_on', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('status', models.CharField(default='pending', max_length=255)),
            ],
        ),
    ]
