# Generated by Django 3.0.8 on 2021-11-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseentry',
            name='grn_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseentry',
            name='grn_status',
            field=models.CharField(blank=True, default='no', max_length=255, null=True),
        ),
    ]
