# Generated by Django 3.0.8 on 2021-11-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0008_auto_20211114_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
