# Generated by Django 3.0.8 on 2021-11-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0009_notification_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsentry',
            name='purchase_order_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseentry',
            name='purchase_order_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
