# Generated by Django 3.0.8 on 2021-11-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0010_auto_20211114_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='invoice_status',
            field=models.CharField(default='no', max_length=255),
        ),
    ]
