# Generated by Django 3.0.8 on 2021-11-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0011_goods_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='invoice_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
