# Generated by Django 3.0.8 on 2021-11-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0012_goods_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsentry',
            name='purchase_order_number',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseentry',
            name='purchase_order_number',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
