# Generated by Django 3.0.8 on 2021-11-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0013_auto_20211114_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialissueentry',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='materialissueentry',
            name='receiving_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
