# Generated by Django 3.0.8 on 2021-11-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0014_auto_20211115_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialissueentry',
            name='receiving_location',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='materialissueentry',
            name='vehicle_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
