# Generated by Django 3.0.8 on 2021-11-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0015_auto_20211119_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='narration',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='goodsentry',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseentry',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
