# Generated by Django 3.0.8 on 2021-11-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0016_auto_20211128_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='purchase_location',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
