# Generated by Django 3.0.8 on 2021-11-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0017_purchaseitem_purchase_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsentry',
            name='vehicle_number',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='grn',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseentry',
            name='vehicle_number',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
