# Generated by Django 3.0.8 on 2021-11-30 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0018_auto_20211130_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('url', models.CharField(default='', max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('stock_category', models.CharField(max_length=255)),
                ('uom', models.CharField(max_length=255)),
                ('stock_type', models.CharField(max_length=255)),
                ('entry_by', models.CharField(default='', max_length=255)),
                ('user_site', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
            ],
        ),
    ]
