# Generated by Django 3.0.8 on 2021-12-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0019_stockitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='item_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
