# Generated by Django 3.0.8 on 2021-12-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0020_stockentry_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsentry',
            name='narration',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internaltransfer',
            name='narration',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='materialissueentry',
            name='narration',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseentry',
            name='narration',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
