# Generated by Django 3.0.8 on 2021-12-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0021_auto_20211201_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaltransfer',
            name='itn_count',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='internaltransfer',
            name='itn_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='materialissueentry',
            name='mie_count',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='materialissueentry',
            name='mie_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
