# Generated by Django 3.0.8 on 2021-12-01 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0022_auto_20211201_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalGrn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_by', models.CharField(max_length=255)),
                ('grn_number', models.CharField(max_length=255)),
                ('grn_count', models.CharField(default='', max_length=255)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('entry_date', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('user_site', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('invoice_id', models.CharField(default='', max_length=255)),
                ('invoice_status', models.CharField(default='no', max_length=255)),
                ('narration', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternalGrnItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsid', models.CharField(max_length=255)),
                ('grn', models.CharField(default='', max_length=255)),
                ('pvn', models.CharField(default='', max_length=255)),
                ('item_id', models.CharField(default='', max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('uom', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('remark', models.CharField(max_length=255)),
                ('invoice_id', models.CharField(default='', max_length=255)),
                ('invoice_status', models.CharField(default='no', max_length=255)),
            ],
        ),
    ]
