# Generated by Django 3.0.8 on 2021-12-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0023_internalgrn_internalgrnitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferitem',
            name='pvn',
            field=models.CharField(default='', max_length=255),
        ),
    ]
