# Generated by Django 3.0.8 on 2022-02-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0025_auto_20220206_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='number_type',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='po_vehi',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vehicle_number',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vehicle_type',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vehicle_type_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maintainancebill',
            name='supplier_address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maintainancebill',
            name='supplier_contact',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maintainancebill',
            name='supplier_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maintainancebill',
            name='supplier_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
