# Generated by Django 3.0.8 on 2022-03-26 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0026_auto_20220225_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.CharField(max_length=100)),
                ('supplier_id', models.CharField(max_length=255)),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_contact', models.CharField(max_length=255)),
                ('supplier_address', models.CharField(default='', max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('remaining', models.CharField(max_length=255)),
                ('pay_method', models.CharField(blank=True, max_length=255, null=True)),
                ('bank', models.CharField(blank=True, max_length=255, null=True)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('entry_by', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('user_site', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_number', models.CharField(max_length=255)),
                ('goodsid', models.CharField(max_length=255)),
                ('purchase_order_number', models.CharField(default='', max_length=255)),
                ('voucher_number', models.CharField(max_length=255)),
                ('supplier', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MaintainInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintainid', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('maintain_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('purchase_order_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('voucher_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('invoice_type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('supplier', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('sub_total', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('discount_per', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('discount_amt', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('vat', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('total', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_amt',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_per',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='grn_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='grn_status',
            field=models.CharField(blank=True, default='no', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='issue_use',
            field=models.CharField(blank=True, default='no', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='po',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintainanceitem',
            name='pvn',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='materialissueentry',
            name='issue_for',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='materialissueentry',
            name='purchase_order_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='materialitem',
            name='po',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='materialitem',
            name='pvn',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseentry',
            name='day',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseentry',
            name='issue_use',
            field=models.CharField(blank=True, default='no', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseentry',
            name='transaction_type',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='issue_use',
            field=models.CharField(blank=True, default='no', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='status',
            field=models.CharField(default='no', max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='issue_use',
            field=models.CharField(blank=True, default='no', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='opening',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='goodsentry',
            name='supplier_address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='goodsentry',
            name='supplier_contact',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='goodsentry',
            name='supplier_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='goodsentry',
            name='supplier_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='grn_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='invoice_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
