# Generated by Django 3.0.8 on 2022-03-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0027_auto_20220326_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintainancebill',
            name='problem_category',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
