# Generated by Django 3.0.8 on 2022-03-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0028_auto_20220328_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelist',
            name='chasis_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelist',
            name='engine_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
