# Generated by Django 3.0.8 on 2022-04-20 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0029_auto_20220330_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_by', models.CharField(max_length=255)),
                ('purchase_order_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('damage_number', models.CharField(max_length=255)),
                ('pvn_count', models.CharField(default='', max_length=255)),
                ('entry_date', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('user_site', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pvn_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pvn_status', models.CharField(blank=True, default='no', max_length=255, null=True)),
                ('narration', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('issue_use', models.CharField(blank=True, default='no', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DamageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damageid', models.CharField(max_length=255)),
                ('po', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('grn', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pvn', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('item_id', models.CharField(default='', max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('uom', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('issue_use', models.CharField(blank=True, default='no', max_length=255, null=True)),
                ('pvn_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pvn_status', models.CharField(blank=True, default='no', max_length=255, null=True)),
            ],
        ),
    ]
