# Generated by Django 3.0.8 on 2022-05-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0030_damageentry_damageitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damageid', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('damage_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('purchase_order_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('voucher_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('invoice_type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('supplier', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('sub_total', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('discount_per', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('discount_amt', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('vat', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('total', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='damageitem',
            old_name='grn',
            new_name='dn',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='damage',
            field=models.CharField(blank=True, default='no', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='damage_qty',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='retur',
            field=models.CharField(blank=True, default='no', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='retur_qty',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseentry',
            name='damage',
            field=models.CharField(blank=True, default='no', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseentry',
            name='retur',
            field=models.CharField(blank=True, default='no', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='damage',
            field=models.CharField(blank=True, default='no', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='damage_qty',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='retur',
            field=models.CharField(blank=True, default='no', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='retur_qty',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
    ]
