# Generated by Django 3.0.8 on 2022-05-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0031_auto_20220510_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='orig_quantity',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='useable_quantity',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
