# Generated by Django 3.0.8 on 2022-05-14 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0032_auto_20220513_0522'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_by', models.CharField(max_length=255)),
                ('purchase_order_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('damage_number', models.CharField(max_length=255)),
                ('pvn_count', models.CharField(default='', max_length=255)),
                ('entry_date', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('user_site', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pvn_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pvn_status', models.CharField(blank=True, default='no', max_length=255, null=True)),
                ('narration', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('issue_use', models.CharField(blank=True, default='no', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damageid', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('damage_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('purchase_order_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('voucher_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('invoice_type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('supplier', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('sub_total', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('discount_per', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('discount_amt', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('vat', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('total', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damageid', models.CharField(max_length=255)),
                ('po', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('dn', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pvn', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('item_id', models.CharField(default='', max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('uom', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('rate', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('discount_per', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('discount_amt', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('amount', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('issue_use', models.CharField(blank=True, default='no', max_length=255, null=True)),
                ('pvn_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pvn_status', models.CharField(blank=True, default='no', max_length=255, null=True)),
            ],
        ),
    ]
