# Generated by Django 3.0.8 on 2022-06-02 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0033_returnentry_returninvoice_returnitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('move_count', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('entry_date', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=255, null=True)),
                ('from_site', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('to_site', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('vehicle_type_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=255, null=True)),
                ('num_type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('user_site', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('entry_by', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('status', models.CharField(blank=True, default='travelling', max_length=255, null=True)),
                ('arrival_datetime', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='user_type',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
