# Generated by Django 3.0.8 on 2022-06-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0034_auto_20220602_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintainancebill',
            name='bill_type',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maintainancebill',
            name='narration',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
