# Generated by Django 3.0.8 on 2022-07-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0035_auto_20220629_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelbill',
            name='day',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fuelbill',
            name='supplier_address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fuelbill',
            name='supplier_contact',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fuelbill',
            name='supplier_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fuelbill',
            name='supplier_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fuelbill',
            name='transaction_type',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
