# Generated by Django 3.0.8 on 2022-07-26 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0036_auto_20220720_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=255)),
                ('cat_url', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('entry_by', models.CharField(default='', max_length=255)),
                ('user_site', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='stockentry',
            name='cat_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='stock_subcategory',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='subcat_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='cat_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='stock_subcategory',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='subcat_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
