# Generated by Django 3.0.8 on 2022-08-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0037_auto_20220726_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
