# Generated by Django 3.0.8 on 2022-08-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0038_auto_20220804_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='main_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
