# Generated by Django 3.0.8 on 2022-08-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0039_stockitem_main_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
