# Generated by Django 3.0.8 on 2022-08-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0040_auto_20220810_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelbill',
            name='narration',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fuelpurchase',
            name='narration',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
