# Generated by Django 3.0.8 on 2022-09-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0041_auto_20220829_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelInternalTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_number', models.CharField(max_length=255)),
                ('from_reserviour', models.CharField(max_length=255)),
                ('to_reserviour', models.CharField(max_length=255)),
                ('quantity', models.CharField(blank=True, max_length=255, null=True)),
                ('user_site', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('entry_by', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('entry_date', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pon', models.IntegerField(default=0)),
                ('fuel_type', models.CharField(default='', max_length=255)),
                ('narration', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
