# Generated by Django 3.0.8 on 2022-10-10 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0042_fuelinternaltransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelLeakage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.CharField(max_length=255)),
                ('leakage_number', models.CharField(default='', max_length=255)),
                ('fcn', models.IntegerField(default=0)),
                ('fuel_type', models.CharField(default='', max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('user_site', models.CharField(default='', max_length=255)),
                ('reserviour', models.CharField(default='', max_length=255)),
                ('reserviour_id', models.CharField(default='', max_length=255)),
                ('entry_datetime_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('entry_date_on', models.DateField(blank=True, default=datetime.date.today)),
                ('entry_by', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternalDamageEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_by', models.CharField(max_length=255)),
                ('damage_number', models.CharField(max_length=255)),
                ('pvn_count', models.CharField(default='', max_length=255)),
                ('entry_date', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('user_site', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pvn_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pvn_status', models.CharField(blank=True, default='no', max_length=255, null=True)),
                ('narration', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('issue_use', models.CharField(blank=True, default='no', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternalDamageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damageid', models.CharField(max_length=255)),
                ('dn', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pvn', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('item_id', models.CharField(default='', max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('uom', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('issue_use', models.CharField(blank=True, default='no', max_length=255, null=True)),
                ('pvn_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pvn_status', models.CharField(blank=True, default='no', max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='internalgrn',
            name='damage',
            field=models.CharField(blank=True, default='no', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internalgrnitems',
            name='damage',
            field=models.CharField(blank=True, default='no', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internalgrnitems',
            name='damage_qty',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internalgrnitems',
            name='orig_quantity',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internaltransfer',
            name='grn_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internaltransfer',
            name='grn_status',
            field=models.CharField(blank=True, default='no', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintainancebill',
            name='gjorder',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintainancebill',
            name='jorder',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintainanceitem',
            name='itnn',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='active_status',
            field=models.CharField(blank=True, default='yes', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='grn_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='grn_status',
            field=models.CharField(blank=True, default='no', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelist',
            name='active_status',
            field=models.CharField(blank=True, default='yes', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelist',
            name='current',
            field=models.CharField(blank=True, default='Chitwan', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internalgrn',
            name='invoice_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internalgrnitems',
            name='invoice_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internalgrnitems',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maintainancebill',
            name='bill_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='maintainancebill',
            name='narration',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content_val',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='from_site',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='from_user',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notify_topic',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
