# Generated by Django 3.0.8 on 2022-10-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0043_auto_20221010_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintainancebill',
            name='narration',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
