# Generated by Django 3.0.8 on 2022-10-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0044_auto_20221010_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintainancebill',
            name='bill_type',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
