# Generated by Django 3.0.8 on 2026-08-18 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproc', '0045_auto_20221010_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLetterhead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Corporate Master Letterhead', max_length=255)),
                ('letterhead_image', models.ImageField(upload_to='letterheads/')),
                ('footer_image', models.ImageField(blank=True, null=True, upload_to='letterheads/footers/')),
                ('site', models.CharField(blank=True, default='All Sites', max_length=255, null=True)),
                ('header_height_cm', models.FloatField(default=3.5, help_text='Height reserved for the header banner in cm')),
                ('top_margin_cm', models.FloatField(default=3.8, help_text='Top page margin for report body content in cm')),
                ('bottom_margin_cm', models.FloatField(default=1.5, help_text='Bottom page margin in cm')),
                ('left_margin_cm', models.FloatField(default=1.2, help_text='Left page margin in cm')),
                ('right_margin_cm', models.FloatField(default=1.2, help_text='Right page margin in cm')),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_by', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
    ]
